import type { Creator } from '@/types'

export const mockCreators: Creator[] = [
  // Instagram Lifestyle/Beauty (20)
  {
    id: 'mock-1', external_id: 'ig-1', handle: 'sophiastylediaries', full_name: 'Sophia Chen',
    platform: 'Instagram', profile_url: 'https://instagram.com/sophiastylediaries',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=sophia',
    bio: 'Lifestyle & beauty creator. NYC-based. Obsessed with skincare, aesthetics & slow living.',
    follower_count: 89000, engagement_rate: 4.2, avg_likes: 3738, avg_comments: 210, avg_views: 12000,
    audience_demographics: { age_18_24: 38, age_25_34: 42, age_35_44: 14, age_45_plus: 6, female: 82, male: 18, top_countries: ['US', 'UK', 'AU'] },
    categories: ['beauty', 'lifestyle', 'skincare'], past_brand_deals: ['beauty', 'fashion', 'wellness'],
    estimated_cpm: 12, estimated_rate_per_post: 1200, contact_email: 'sophia@stylediaries.com',
    location: 'New York, USA', brand_safety_score: 95, fake_follower_percentage: 3.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Morning skincare routine you NEED 🌿', 'NYC apartment tour ✨', 'GRWM: date night look 💄', 'Best drugstore finds under $20', 'Self-care Sunday essentials']
  },
  {
    id: 'mock-2', external_id: 'ig-2', handle: 'bellabeautyblog', full_name: 'Isabella Martinez',
    platform: 'Instagram', profile_url: 'https://instagram.com/bellabeautyblog',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=bella',
    bio: 'Beauty enthusiast | MUA | Sharing makeup tutorials & product reviews daily.',
    follower_count: 245000, engagement_rate: 2.8, avg_likes: 6860, avg_comments: 380, avg_views: 35000,
    audience_demographics: { age_18_24: 45, age_25_34: 38, age_35_44: 12, age_45_plus: 5, female: 91, male: 9, top_countries: ['US', 'MX', 'ES'] },
    categories: ['beauty', 'makeup', 'tutorials'], past_brand_deals: ['beauty', 'cosmetics', 'fashion'],
    estimated_cpm: 9, estimated_rate_per_post: 2800, contact_email: 'bella@beautyblogs.com',
    location: 'Los Angeles, USA', brand_safety_score: 92, fake_follower_percentage: 4.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['Full glam tutorial using only drugstore 👄', 'Dupe alert! $8 vs $50 foundation', 'My holy grail skincare products', 'Blush placement tutorial for beginners', 'Honest review: viral TikTok products']
  },
  {
    id: 'mock-3', external_id: 'ig-3', handle: 'minamoments', full_name: 'Mina Park',
    platform: 'Instagram', profile_url: 'https://instagram.com/minamoments',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=mina',
    bio: 'Korean beauty & lifestyle. Sharing my world one photo at a time 🌸',
    follower_count: 52000, engagement_rate: 6.1, avg_likes: 3172, avg_comments: 145, avg_views: 7000,
    audience_demographics: { age_18_24: 52, age_25_34: 35, age_35_44: 9, age_45_plus: 4, female: 78, male: 22, top_countries: ['US', 'KR', 'JP'] },
    categories: ['kbeauty', 'lifestyle', 'fashion'], past_brand_deals: ['skincare', 'kbeauty', 'food'],
    estimated_cpm: 14, estimated_rate_per_post: 900, contact_email: 'mina@moments.co',
    location: 'San Francisco, USA', brand_safety_score: 97, fake_follower_percentage: 2.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['K-beauty haul that changed my skin 🌿', 'Cozy Seoul cafe aesthetic ☕', 'My current skincare shelf', 'Outfit inspo: Korea street style', '5 step morning routine']
  },
  {
    id: 'mock-4', external_id: 'ig-4', handle: 'luxeliving_emma', full_name: 'Emma Whitfield',
    platform: 'Instagram', profile_url: 'https://instagram.com/luxeliving_emma',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=emma',
    bio: 'Luxury lifestyle, interiors & fashion. London-based creative.',
    follower_count: 412000, engagement_rate: 1.9, avg_likes: 7828, avg_comments: 412, avg_views: 58000,
    audience_demographics: { age_18_24: 28, age_25_34: 48, age_35_44: 18, age_45_plus: 6, female: 74, male: 26, top_countries: ['UK', 'US', 'AE'] },
    categories: ['luxury', 'lifestyle', 'fashion', 'interiors'], past_brand_deals: ['fashion', 'luxury', 'beauty', 'travel'],
    estimated_cpm: 8, estimated_rate_per_post: 4500, contact_email: 'emma@luxeliving.co.uk',
    location: 'London, UK', brand_safety_score: 93, fake_follower_percentage: 5.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['London morning walks 🌿', 'Flat tour — our living room refresh', 'What I wore to Paris fashion week', 'Luxury hotel review: Claridges', 'My capsule wardrobe essentials']
  },
  {
    id: 'mock-5', external_id: 'ig-5', handle: 'glowithalex', full_name: 'Alexandra Torres',
    platform: 'Instagram', profile_url: 'https://instagram.com/glowithalex',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=alex',
    bio: 'Glow inside & out ✨ Skincare obsessed. Latina. Sharing what actually works.',
    follower_count: 31000, engagement_rate: 7.4, avg_likes: 2294, avg_comments: 98, avg_views: 4500,
    audience_demographics: { age_18_24: 48, age_25_34: 38, age_35_44: 10, age_45_plus: 4, female: 85, male: 15, top_countries: ['US', 'MX', 'CO'] },
    categories: ['skincare', 'beauty', 'wellness'], past_brand_deals: ['skincare', 'wellness'],
    estimated_cpm: 16, estimated_rate_per_post: 650, contact_email: 'alex@glowwithalex.com',
    location: 'Miami, USA', brand_safety_score: 98, fake_follower_percentage: 1.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Honest hyperpigmentation routine update', 'GRWM for a content day', 'SPF non-negotiable roundup ☀️', 'Skin barrier repair routine', '3 months on new skincare — results!']
  },
  {
    id: 'mock-6', external_id: 'ig-6', handle: 'dailydoseofchic', full_name: 'Camille Dubois',
    platform: 'Instagram', profile_url: 'https://instagram.com/dailydoseofchic',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=camille',
    bio: 'French girl aesthetic. Parisian fashion & beauty secrets. Effortless style.',
    follower_count: 178000, engagement_rate: 3.2, avg_likes: 5696, avg_comments: 298, avg_views: 25000,
    audience_demographics: { age_18_24: 35, age_25_34: 45, age_35_44: 16, age_45_plus: 4, female: 80, male: 20, top_countries: ['FR', 'US', 'CA'] },
    categories: ['fashion', 'beauty', 'lifestyle'], past_brand_deals: ['fashion', 'beauty', 'food', 'travel'],
    estimated_cpm: 10, estimated_rate_per_post: 2200, contact_email: 'camille@dailychic.fr',
    location: 'Paris, France', brand_safety_score: 91, fake_follower_percentage: 4.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Le look du jour 🥐', 'My French girl skincare routine', 'Paris flea market finds', 'How to look chic for under €50', 'Autumn wardrobe transitions']
  },
  {
    id: 'mock-7', external_id: 'ig-7', handle: 'sunsetbeautyco', full_name: 'Jasmine Okafor',
    platform: 'Instagram', profile_url: 'https://instagram.com/sunsetbeautyco',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=jasmine',
    bio: 'Black beauty creator. Celebrating melanin & texture. Product reviews & tutorials.',
    follower_count: 67000, engagement_rate: 5.8, avg_likes: 3886, avg_comments: 220, avg_views: 9500,
    audience_demographics: { age_18_24: 42, age_25_34: 40, age_35_44: 13, age_45_plus: 5, female: 88, male: 12, top_countries: ['US', 'NG', 'UK'] },
    categories: ['beauty', 'haircare', 'skincare'], past_brand_deals: ['beauty', 'haircare', 'wellness'],
    estimated_cpm: 13, estimated_rate_per_post: 1100, contact_email: 'jasmine@sunsetbeauty.com',
    location: 'Atlanta, USA', brand_safety_score: 96, fake_follower_percentage: 2.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['4C hair wash day routine 🌿', 'Products that actually work for dark skin', 'Natural hair journey update', 'Protective style inspo', 'Holy grail products for melanin skin']
  },
  {
    id: 'mock-8', external_id: 'ig-8', handle: 'prettylittlethingsby_sarah', full_name: 'Sarah Kim',
    platform: 'Instagram', profile_url: 'https://instagram.com/prettylittlethingsby_sarah',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=sarah',
    bio: 'Minimalist beauty. Less is more. Sharing simple routines that work.',
    follower_count: 22000, engagement_rate: 8.1, avg_likes: 1782, avg_comments: 84, avg_views: 3200,
    audience_demographics: { age_18_24: 40, age_25_34: 44, age_35_44: 12, age_45_plus: 4, female: 83, male: 17, top_countries: ['US', 'KR', 'CA'] },
    categories: ['beauty', 'skincare', 'minimalism'], past_brand_deals: ['skincare', 'wellness'],
    estimated_cpm: 18, estimated_rate_per_post: 520, contact_email: 'sarah@prettylittlethings.com',
    location: 'Seattle, USA', brand_safety_score: 99, fake_follower_percentage: 1.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['3 products, perfect skin ✨', 'The only foundation you need', 'Morning routine under 5 minutes', 'Clean beauty swaps worth it', 'Honest: before/after retinol 6mo']
  },
  {
    id: 'mock-9', external_id: 'ig-9', handle: 'wanderandblossom', full_name: 'Lily Nguyen',
    platform: 'Instagram', profile_url: 'https://instagram.com/wanderandblossom',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=lily',
    bio: 'Beauty, culture & wanderlust. Vietnamese-American creator. NYC.',
    follower_count: 143000, engagement_rate: 3.6, avg_likes: 5148, avg_comments: 262, avg_views: 20000,
    audience_demographics: { age_18_24: 40, age_25_34: 42, age_35_44: 13, age_45_plus: 5, female: 79, male: 21, top_countries: ['US', 'VN', 'AU'] },
    categories: ['beauty', 'travel', 'culture'], past_brand_deals: ['beauty', 'travel', 'food'],
    estimated_cpm: 11, estimated_rate_per_post: 1900, contact_email: 'lily@wanderandblossom.com',
    location: 'New York, USA', brand_safety_score: 94, fake_follower_percentage: 3.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Exploring Hanoi for the first time 🌸', 'Street food I ate in Vietnam', 'Airport beauty essentials', 'Glow routine for travel days', 'My NYC beauty spots']
  },
  {
    id: 'mock-10', external_id: 'ig-10', handle: 'thebeautybossrose', full_name: 'Rose Thompson',
    platform: 'Instagram', profile_url: 'https://instagram.com/thebeautybossrose',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=rose',
    bio: 'Makeup artist turned content creator. Product reviews & tutorials. Chicago.',
    follower_count: 98000, engagement_rate: 4.0, avg_likes: 3920, avg_comments: 198, avg_views: 14000,
    audience_demographics: { age_18_24: 38, age_25_34: 44, age_35_44: 14, age_45_plus: 4, female: 87, male: 13, top_countries: ['US', 'UK', 'CA'] },
    categories: ['beauty', 'makeup', 'tutorials'], past_brand_deals: ['beauty', 'cosmetics', 'fashion'],
    estimated_cpm: 12, estimated_rate_per_post: 1400, contact_email: 'rose@beautyboss.com',
    location: 'Chicago, USA', brand_safety_score: 94, fake_follower_percentage: 3.0,
    last_updated: new Date().toISOString(),
    sample_captions: ['Pro tips for flawless base', 'Tools every MUA needs', 'Quick everyday glam', 'Bridal makeup trial', 'Foundation match guide']
  },
  {
    id: 'mock-11', external_id: 'ig-11', handle: 'chloestylechronicles', full_name: 'Chloe Adams',
    platform: 'Instagram', profile_url: 'https://instagram.com/chloestylechronicles',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=chloe',
    bio: 'Fashion & lifestyle | Sustainable style advocate | London',
    follower_count: 38000, engagement_rate: 5.9, avg_likes: 2242, avg_comments: 118, avg_views: 5500,
    audience_demographics: { age_18_24: 36, age_25_34: 48, age_35_44: 12, age_45_plus: 4, female: 76, male: 24, top_countries: ['UK', 'US', 'AU'] },
    categories: ['fashion', 'sustainability', 'lifestyle'], past_brand_deals: ['fashion', 'sustainable brands'],
    estimated_cpm: 14, estimated_rate_per_post: 700, contact_email: 'chloe@stylechronicles.co.uk',
    location: 'London, UK', brand_safety_score: 96, fake_follower_percentage: 2.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Thrift haul 🌱', 'Sustainable fashion brands I love', 'Slow fashion philosophy', 'Capsule wardrobe for spring', 'Secondhand luxury finds']
  },
  {
    id: 'mock-12', external_id: 'ig-12', handle: 'glowupwithgrace', full_name: 'Grace Johnson',
    platform: 'Instagram', profile_url: 'https://instagram.com/glowupwithgrace',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=grace',
    bio: 'Beauty & wellness. Self-care isn\'t selfish. Dallas TX.',
    follower_count: 74000, engagement_rate: 4.8, avg_likes: 3552, avg_comments: 180, avg_views: 10500,
    audience_demographics: { age_18_24: 44, age_25_34: 40, age_35_44: 12, age_45_plus: 4, female: 86, male: 14, top_countries: ['US', 'CA', 'UK'] },
    categories: ['beauty', 'wellness', 'selfcare'], past_brand_deals: ['beauty', 'wellness', 'fitness'],
    estimated_cpm: 13, estimated_rate_per_post: 1100, contact_email: 'grace@glowupwithgrace.com',
    location: 'Dallas, USA', brand_safety_score: 95, fake_follower_percentage: 2.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['Sunday reset routine 🌿', 'What I eat for clear skin', 'Night routine that changed my life', 'Affordable wellness swaps', 'Mental health & self-care tips']
  },
  {
    id: 'mock-13', external_id: 'ig-13', handle: 'vivamakeupstudio', full_name: 'Valentina Reyes',
    platform: 'Instagram', profile_url: 'https://instagram.com/vivamakeupstudio',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=valentina',
    bio: 'Makeup artist. Beauty educator. Miami vibes. Sharing knowledge daily.',
    follower_count: 520000, engagement_rate: 1.8, avg_likes: 9360, avg_comments: 480, avg_views: 72000,
    audience_demographics: { age_18_24: 42, age_25_34: 40, age_35_44: 14, age_45_plus: 4, female: 90, male: 10, top_countries: ['US', 'MX', 'BR'] },
    categories: ['makeup', 'beauty', 'tutorials'], past_brand_deals: ['cosmetics', 'beauty', 'fashion', 'wellness'],
    estimated_cpm: 7, estimated_rate_per_post: 5200, contact_email: 'valentina@vivamakeup.com',
    location: 'Miami, USA', brand_safety_score: 90, fake_follower_percentage: 6.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Editorial makeup breakdown', 'I recreated this viral look', 'Blending secrets pros use', 'Full face using one palette', '5 minute client-ready makeup']
  },
  {
    id: 'mock-14', external_id: 'ig-14', handle: 'nialifestyle', full_name: 'Nia Williams',
    platform: 'Instagram', profile_url: 'https://instagram.com/nialifestyle',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=nia',
    bio: 'Lifestyle creator. Mom life + beauty. Real & relatable. Chicago.',
    follower_count: 61000, engagement_rate: 5.2, avg_likes: 3172, avg_comments: 165, avg_views: 8800,
    audience_demographics: { age_18_24: 25, age_25_34: 50, age_35_44: 20, age_45_plus: 5, female: 84, male: 16, top_countries: ['US', 'UK', 'CA'] },
    categories: ['lifestyle', 'beauty', 'parenting'], past_brand_deals: ['beauty', 'wellness', 'family'],
    estimated_cpm: 14, estimated_rate_per_post: 1000, contact_email: 'nia@nialifestyle.com',
    location: 'Chicago, USA', brand_safety_score: 97, fake_follower_percentage: 2.3,
    last_updated: new Date().toISOString(),
    sample_captions: ['Mom life & self-care balance', 'Quick makeup when you\'re a parent', 'Products I swear by as a busy mom', 'Real talk: mental health update', 'Family Sunday routine 🏡']
  },
  {
    id: 'mock-15', external_id: 'ig-15', handle: 'peachbeautydiaries', full_name: 'Peach Li',
    platform: 'Instagram', profile_url: 'https://instagram.com/peachbeautydiaries',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=peach',
    bio: 'Beauty + lifestyle in Singapore 🍑 Sharing my faves from Asia & beyond.',
    follower_count: 45000, engagement_rate: 6.3, avg_likes: 2835, avg_comments: 142, avg_views: 6500,
    audience_demographics: { age_18_24: 46, age_25_34: 40, age_35_44: 10, age_45_plus: 4, female: 81, male: 19, top_countries: ['SG', 'MY', 'US'] },
    categories: ['beauty', 'kbeauty', 'lifestyle'], past_brand_deals: ['skincare', 'beauty', 'food'],
    estimated_cpm: 15, estimated_rate_per_post: 820, contact_email: 'peach@beautydiaries.sg',
    location: 'Singapore', brand_safety_score: 96, fake_follower_percentage: 2.0,
    last_updated: new Date().toISOString(),
    sample_captions: ['Singapore summer skincare routine', 'Best beauty buys in Korea', 'Affordable dupes for luxury products', 'My most-used lip products', 'Haul from my Seoul trip 🛍️']
  },
  {
    id: 'mock-16', external_id: 'ig-16', handle: 'theaestheticdiaries', full_name: 'Zoe Harrison',
    platform: 'Instagram', profile_url: 'https://instagram.com/theaestheticdiaries',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=zoe',
    bio: 'Aesthetic living. Fashion, interiors, beauty. Based in Sydney, Australia.',
    follower_count: 193000, engagement_rate: 2.9, avg_likes: 5597, avg_comments: 286, avg_views: 27000,
    audience_demographics: { age_18_24: 38, age_25_34: 44, age_35_44: 14, age_45_plus: 4, female: 77, male: 23, top_countries: ['AU', 'US', 'UK'] },
    categories: ['lifestyle', 'fashion', 'interiors'], past_brand_deals: ['fashion', 'beauty', 'home', 'wellness'],
    estimated_cpm: 10, estimated_rate_per_post: 2400, contact_email: 'zoe@aestheticdiaries.com.au',
    location: 'Sydney, Australia', brand_safety_score: 93, fake_follower_percentage: 4.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Sydney summer essentials 🌊', 'My apartment makeover reveal', 'Neutral wardrobe essentials', 'Top Bondi café finds', 'How I curate my feed aesthetic']
  },
  {
    id: 'mock-17', external_id: 'ig-17', handle: 'beautybypriya', full_name: 'Priya Sharma',
    platform: 'Instagram', profile_url: 'https://instagram.com/beautybypriya',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=priya',
    bio: 'South Asian beauty creator. Celebrating brown skin. Bridal & everyday glam.',
    follower_count: 79000, engagement_rate: 4.6, avg_likes: 3634, avg_comments: 196, avg_views: 11000,
    audience_demographics: { age_18_24: 40, age_25_34: 44, age_35_44: 12, age_45_plus: 4, female: 88, male: 12, top_countries: ['IN', 'US', 'UK'] },
    categories: ['beauty', 'bridal', 'south-asian'], past_brand_deals: ['beauty', 'fashion', 'jewelry'],
    estimated_cpm: 13, estimated_rate_per_post: 1200, contact_email: 'priya@beautybypriya.in',
    location: 'London, UK', brand_safety_score: 95, fake_follower_percentage: 2.7,
    last_updated: new Date().toISOString(),
    sample_captions: ['Brown skin makeup tutorial 🌟', 'Bridal prep: 30 days out', 'Shade range review — are they inclusive?', 'Desi wedding glam look', 'My go-to products for tan skin']
  },
  {
    id: 'mock-18', external_id: 'ig-18', handle: 'luxeskin_marie', full_name: 'Marie Laurent',
    platform: 'Instagram', profile_url: 'https://instagram.com/luxeskin_marie',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=marie',
    bio: 'Skincare sommelier. Luxury & drugstore. Science-based. Paris/NYC.',
    follower_count: 164000, engagement_rate: 3.4, avg_likes: 5576, avg_comments: 284, avg_views: 23000,
    audience_demographics: { age_18_24: 30, age_25_34: 50, age_35_44: 16, age_45_plus: 4, female: 80, male: 20, top_countries: ['US', 'FR', 'CA'] },
    categories: ['skincare', 'beauty', 'science'], past_brand_deals: ['skincare', 'wellness', 'luxury'],
    estimated_cpm: 11, estimated_rate_per_post: 2100, contact_email: 'marie@luxeskin.com',
    location: 'Paris/New York', brand_safety_score: 94, fake_follower_percentage: 3.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Science behind hyaluronic acid', 'Is expensive serum worth it?', 'Dermatologist-approved routine', '6 month tretinoin update', 'Ingredients that actually work']
  },
  {
    id: 'mock-19', external_id: 'ig-19', handle: 'makeupwithamber', full_name: 'Amber Collins',
    platform: 'Instagram', profile_url: 'https://instagram.com/makeupwithamber',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=amber',
    bio: 'Teaching the world one makeup look at a time. Tutorial queen.',
    follower_count: 310000, engagement_rate: 2.5, avg_likes: 7750, avg_comments: 390, avg_views: 44000,
    audience_demographics: { age_18_24: 48, age_25_34: 38, age_35_44: 11, age_45_plus: 3, female: 92, male: 8, top_countries: ['US', 'UK', 'CA'] },
    categories: ['makeup', 'tutorials', 'beauty'], past_brand_deals: ['cosmetics', 'beauty', 'fashion'],
    estimated_cpm: 8, estimated_rate_per_post: 3200, contact_email: 'amber@makeupwithamber.com',
    location: 'Nashville, USA', brand_safety_score: 91, fake_follower_percentage: 5.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['Bold liner for beginners 👁️', 'Recreating celebrity looks', 'Everyday glam under 15 minutes', 'Must-have makeup brushes', 'Contouring for different face shapes']
  },
  {
    id: 'mock-20', external_id: 'ig-20', handle: 'themodernwitch_beauty', full_name: 'Luna Black',
    platform: 'Instagram', profile_url: 'https://instagram.com/themodernwitch_beauty',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=luna',
    bio: 'Alt beauty. Dark aesthetics. Indie brands. Portland.',
    follower_count: 42000, engagement_rate: 7.2, avg_likes: 3024, avg_comments: 158, avg_views: 6000,
    audience_demographics: { age_18_24: 55, age_25_34: 35, age_35_44: 8, age_45_plus: 2, female: 70, male: 30, top_countries: ['US', 'UK', 'DE'] },
    categories: ['alt-beauty', 'indie', 'fashion'], past_brand_deals: ['indie beauty', 'fashion', 'accessories'],
    estimated_cpm: 15, estimated_rate_per_post: 780, contact_email: 'luna@modernwitch.com',
    location: 'Portland, USA', brand_safety_score: 88, fake_follower_percentage: 2.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Dark academia makeup inspo 🖤', 'Indie brand gems you\'re sleeping on', 'Gothic glam for everyday', 'My aesthetic: autumn witch vibes', 'Current alt beauty favorites']
  },
  // TikTok Gen Z Fashion/Food/Comedy (15)
  {
    id: 'mock-21', external_id: 'tt-1', handle: 'fashionfrenzy_kai', full_name: 'Kai Johnson',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@fashionfrenzy_kai',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=kai',
    bio: 'Gen Z fashion POV. Thrifted fits. Viral trends. Chicago.',
    follower_count: 380000, engagement_rate: 8.4, avg_likes: 31920, avg_comments: 1520, avg_views: 420000,
    audience_demographics: { age_18_24: 65, age_25_34: 28, age_35_44: 5, age_45_plus: 2, female: 62, male: 38, top_countries: ['US', 'UK', 'AU'] },
    categories: ['fashion', 'gen-z', 'thrift'], past_brand_deals: ['fashion', 'accessories', 'beauty'],
    estimated_cpm: 6, estimated_rate_per_post: 3200, contact_email: 'kai@fashionfrenzy.com',
    location: 'Chicago, USA', brand_safety_score: 89, fake_follower_percentage: 6.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['POV: you found the fit at the thrift store', 'Rating my fits from $5 to $500', 'Fashion week fits I could never afford 😭', 'GRWM for a vintage show', 'Why streetwear is taking over']
  },
  {
    id: 'mock-22', external_id: 'tt-2', handle: 'foodiefinds_maya', full_name: 'Maya Chen',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@foodiefinds_maya',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=maya',
    bio: 'Eating my way through life 🍜 NYC food content. Honest reviews.',
    follower_count: 1200000, engagement_rate: 6.2, avg_likes: 74400, avg_comments: 3800, avg_views: 1800000,
    audience_demographics: { age_18_24: 52, age_25_34: 36, age_35_44: 9, age_45_plus: 3, female: 55, male: 45, top_countries: ['US', 'CA', 'AU'] },
    categories: ['food', 'restaurants', 'reviews'], past_brand_deals: ['food', 'delivery', 'cooking'],
    estimated_cpm: 4, estimated_rate_per_post: 8500, contact_email: 'maya@foodiefinds.com',
    location: 'New York, USA', brand_safety_score: 93, fake_follower_percentage: 7.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['I tried every dumpling in NYC 🥟', 'Rating viral foods so you don\'t have to', 'Hidden gem restaurants in Flushing', 'Budget vs fancy: same dish', 'This is the best food in NYC fight me']
  },
  {
    id: 'mock-23', external_id: 'tt-3', handle: 'comedyqueen_zara', full_name: 'Zara Osei',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@comedyqueen_zara',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=zara',
    bio: 'Making you laugh since 2020 😂 Comedy skits & relatable content.',
    follower_count: 2100000, engagement_rate: 9.1, avg_likes: 191100, avg_comments: 8400, avg_views: 3500000,
    audience_demographics: { age_18_24: 60, age_25_34: 30, age_35_44: 7, age_45_plus: 3, female: 58, male: 42, top_countries: ['US', 'UK', 'CA'] },
    categories: ['comedy', 'entertainment', 'lifestyle'], past_brand_deals: ['fashion', 'food', 'tech', 'beauty'],
    estimated_cpm: 3, estimated_rate_per_post: 12000, contact_email: 'zara@comedyqueen.com',
    location: 'Los Angeles, USA', brand_safety_score: 85, fake_follower_percentage: 8.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['When you forget what you were doing 💀', 'POV: me pretending to be productive', 'Types of people at the gym', 'If brands texted like your ex', 'Gen Z vs millennial humor explained']
  },
  {
    id: 'mock-24', external_id: 'tt-4', handle: 'style.by.noah', full_name: 'Noah Park',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@style.by.noah',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=noah',
    bio: 'Men\'s fashion & style. Making guys look better, one fit at a time.',
    follower_count: 650000, engagement_rate: 7.3, avg_likes: 47450, avg_comments: 2250, avg_views: 920000,
    audience_demographics: { age_18_24: 55, age_25_34: 35, age_35_44: 8, age_45_plus: 2, female: 42, male: 58, top_countries: ['US', 'CA', 'UK'] },
    categories: ['mens-fashion', 'style', 'lifestyle'], past_brand_deals: ['fashion', 'grooming', 'accessories'],
    estimated_cpm: 5, estimated_rate_per_post: 4800, contact_email: 'noah@stylebyn.com',
    location: 'Toronto, Canada', brand_safety_score: 91, fake_follower_percentage: 5.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Affordable outfit formula that works', 'Stop making these style mistakes', 'Capsule wardrobe for guys 2024', 'Rate my 7 day fits', 'This $30 item elevates every outfit']
  },
  {
    id: 'mock-25', external_id: 'tt-5', handle: 'kitchenchaos_leo', full_name: 'Leo Santos',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@kitchenchaos_leo',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=leo',
    bio: 'Self-taught chef. Chaotic cooking content. Brazilian-American. Boston.',
    follower_count: 890000, engagement_rate: 7.8, avg_likes: 69420, avg_comments: 3200, avg_views: 1300000,
    audience_demographics: { age_18_24: 48, age_25_34: 38, age_35_44: 10, age_45_plus: 4, female: 52, male: 48, top_countries: ['US', 'BR', 'CA'] },
    categories: ['cooking', 'food', 'entertainment'], past_brand_deals: ['food', 'cooking', 'delivery'],
    estimated_cpm: 4, estimated_rate_per_post: 6200, contact_email: 'leo@kitchenchaos.com',
    location: 'Boston, USA', brand_safety_score: 92, fake_follower_percentage: 5.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['5 ingredients, restaurant quality pasta 🍝', 'I made Gordon Ramsay\'s recipe worse', 'Street food from Brazil at home', 'Honest: I failed this 3 times', 'Budget meal prep for the whole week']
  },
  {
    id: 'mock-26', external_id: 'tt-6', handle: 'fashionflip_jade', full_name: 'Jade Williams',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@fashionflip_jade',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=jade',
    bio: 'Transforming cheap pieces into looks 💫 OOTD & styling hacks.',
    follower_count: 478000, engagement_rate: 8.9, avg_likes: 42542, avg_comments: 1980, avg_views: 680000,
    audience_demographics: { age_18_24: 68, age_25_34: 26, age_35_44: 4, age_45_plus: 2, female: 74, male: 26, top_countries: ['US', 'UK', 'AU'] },
    categories: ['fashion', 'styling', 'diy'], past_brand_deals: ['fashion', 'accessories', 'beauty'],
    estimated_cpm: 5, estimated_rate_per_post: 3500, contact_email: 'jade@fashionflip.com',
    location: 'Houston, USA', brand_safety_score: 90, fake_follower_percentage: 6.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['$10 dress styled 5 ways', 'Shein vs Zara: honest review', 'Trendy vs timeless pieces', 'How to look expensive on a budget', 'Thrift flip transformation 🔄']
  },
  {
    id: 'mock-27', external_id: 'tt-7', handle: 'midnightmunchies_sam', full_name: 'Sam Rodriguez',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@midnightmunchies_sam',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=sam',
    bio: 'Midnight cooking, comfort food & chaos 🌙 Culinary student.',
    follower_count: 320000, engagement_rate: 8.2, avg_likes: 26240, avg_comments: 1280, avg_views: 450000,
    audience_demographics: { age_18_24: 62, age_25_34: 30, age_35_44: 6, age_45_plus: 2, female: 50, male: 50, top_countries: ['US', 'MX', 'CA'] },
    categories: ['food', 'cooking', 'lifestyle'], past_brand_deals: ['food', 'cooking', 'beverages'],
    estimated_cpm: 6, estimated_rate_per_post: 2600, contact_email: 'sam@midnightmunchies.com',
    location: 'Austin, USA', brand_safety_score: 88, fake_follower_percentage: 5.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['2am mac and cheese recipe 🧀', 'Rating comfort food I ate as a kid', 'Dorm room cooking hacks', 'These snacks are dangerously good', 'Making fancy food at home']
  },
  {
    id: 'mock-28', external_id: 'tt-8', handle: 'gen_z_explained', full_name: 'Tyler Moss',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@gen_z_explained',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=tyler',
    bio: 'Explaining Gen Z culture to millennials (and back) 😂 Comedy skits.',
    follower_count: 1560000, engagement_rate: 9.8, avg_likes: 152880, avg_comments: 7200, avg_views: 2800000,
    audience_demographics: { age_18_24: 58, age_25_34: 32, age_35_44: 8, age_45_plus: 2, female: 55, male: 45, top_countries: ['US', 'UK', 'CA'] },
    categories: ['comedy', 'culture', 'lifestyle'], past_brand_deals: ['tech', 'gaming', 'food', 'fashion'],
    estimated_cpm: 3, estimated_rate_per_post: 10500, contact_email: 'tyler@genzexplained.com',
    location: 'New York, USA', brand_safety_score: 86, fake_follower_percentage: 9.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['When Boomers try to understand TikTok', 'Gen Z dictionary for millennials 📖', 'Things only Gen Z will understand', 'I spent $500 on Gen Z trend items', 'POV: different generations watching the same movie']
  },
  {
    id: 'mock-29', external_id: 'tt-9', handle: 'veganvibes_ava', full_name: 'Ava Green',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@veganvibes_ava',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=ava',
    bio: 'Making vegan food actually look good 🌱 Recipe creator. LA.',
    follower_count: 245000, engagement_rate: 7.5, avg_likes: 18375, avg_comments: 920, avg_views: 350000,
    audience_demographics: { age_18_24: 50, age_25_34: 38, age_35_44: 9, age_45_plus: 3, female: 68, male: 32, top_countries: ['US', 'UK', 'AU'] },
    categories: ['vegan', 'food', 'wellness'], past_brand_deals: ['food', 'wellness', 'beauty'],
    estimated_cpm: 6, estimated_rate_per_post: 2100, contact_email: 'ava@veganvibes.com',
    location: 'Los Angeles, USA', brand_safety_score: 96, fake_follower_percentage: 3.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Vegan meal prep that doesn\'t suck 🌱', 'I went vegan for 30 days, here\'s what happened', 'Recreating fast food dishes but vegan', 'Plant-based that even meat eaters love', 'Budget vegan grocery haul']
  },
  {
    id: 'mock-30', external_id: 'tt-10', handle: 'styletok_river', full_name: 'River Kim',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@styletok_river',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=river',
    bio: 'Non-binary fashion creator. Fluid style. Breaking rules daily. NYC.',
    follower_count: 420000, engagement_rate: 8.6, avg_likes: 36120, avg_comments: 1840, avg_views: 600000,
    audience_demographics: { age_18_24: 62, age_25_34: 30, age_35_44: 6, age_45_plus: 2, female: 54, male: 46, top_countries: ['US', 'UK', 'CA'] },
    categories: ['fashion', 'lgbtq', 'lifestyle'], past_brand_deals: ['fashion', 'beauty', 'accessories'],
    estimated_cpm: 5, estimated_rate_per_post: 3200, contact_email: 'river@styletok.com',
    location: 'New York, USA', brand_safety_score: 90, fake_follower_percentage: 5.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Gender-fluid outfit ideas 🌈', 'Shopping in the men\'s section as a woman', 'Challenging the fashion binary', 'My most authentic outfits ever', 'Androgynous style guide']
  },
  {
    id: 'mock-31', external_id: 'tt-11', handle: 'drinksbydave', full_name: 'Dave Nguyen',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@drinksbydave',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=dave',
    bio: 'Cocktails, mocktails & chaos 🍹 Bartender. Content creator. Denver.',
    follower_count: 560000, engagement_rate: 7.1, avg_likes: 39760, avg_comments: 1960, avg_views: 820000,
    audience_demographics: { age_18_24: 45, age_25_34: 44, age_35_44: 9, age_45_plus: 2, female: 52, male: 48, top_countries: ['US', 'UK', 'CA'] },
    categories: ['drinks', 'food', 'lifestyle'], past_brand_deals: ['beverages', 'food', 'cooking'],
    estimated_cpm: 5, estimated_rate_per_post: 4100, contact_email: 'dave@drinksbydave.com',
    location: 'Denver, USA', brand_safety_score: 84, fake_follower_percentage: 6.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['Recreating fancy cocktails at home 🍸', 'Rating your favorite cocktail orders', 'Mocktail inspo for dry January', '5 cocktails, 1 bottle of whiskey', 'Drunk chef series: episode 1']
  },
  {
    id: 'mock-32', external_id: 'tt-12', handle: 'fashionmicro_eve', full_name: 'Eve Patel',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@fashionmicro_eve',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=eve',
    bio: 'Fashion microinfluencer. Honest reviews. Real budget. UK.',
    follower_count: 48000, engagement_rate: 9.2, avg_likes: 4416, avg_comments: 224, avg_views: 65000,
    audience_demographics: { age_18_24: 55, age_25_34: 36, age_35_44: 7, age_45_plus: 2, female: 72, male: 28, top_countries: ['UK', 'US', 'IE'] },
    categories: ['fashion', 'reviews', 'lifestyle'], past_brand_deals: ['fashion', 'beauty'],
    estimated_cpm: 8, estimated_rate_per_post: 620, contact_email: 'eve@fashionmicroeve.co.uk',
    location: 'Manchester, UK', brand_safety_score: 97, fake_follower_percentage: 2.4,
    last_updated: new Date().toISOString(),
    sample_captions: ['Honest haul: worth it or not?', 'Why I stopped fast fashion (mostly)', 'Fashion on a tight budget', 'Try-on haul, size 14 perspective', 'Building a wardrobe from scratch £500']
  },
  {
    id: 'mock-33', external_id: 'tt-13', handle: 'comedycookingclub', full_name: 'Marcus Brown',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@comedycookingclub',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=marcus',
    bio: 'Teaching cooking through comedy. Dad jokes included. No refunds.',
    follower_count: 730000, engagement_rate: 8.4, avg_likes: 61320, avg_comments: 2920, avg_views: 1100000,
    audience_demographics: { age_18_24: 42, age_25_34: 40, age_35_44: 13, age_45_plus: 5, female: 48, male: 52, top_countries: ['US', 'CA', 'UK'] },
    categories: ['cooking', 'comedy', 'food'], past_brand_deals: ['food', 'cooking', 'beverages'],
    estimated_cpm: 4, estimated_rate_per_post: 5100, contact_email: 'marcus@comedycooking.com',
    location: 'Atlanta, USA', brand_safety_score: 93, fake_follower_percentage: 5.6,
    last_updated: new Date().toISOString(),
    sample_captions: ['I can\'t stop burning things 🔥', 'Reacting to Michelin star vs home cook', 'Making restaurant quality food badly', 'My mom\'s recipe vs the internet\'s', 'Family recipe that\'s been ruined']
  },
  {
    id: 'mock-34', external_id: 'tt-14', handle: 'streetstyle_moni', full_name: 'Monica Tran',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@streetstyle_moni',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=monica',
    bio: 'Street style photographer & fashion creator. Documenting style in the wild. NYC.',
    follower_count: 185000, engagement_rate: 6.8, avg_likes: 12580, avg_comments: 660, avg_views: 270000,
    audience_demographics: { age_18_24: 58, age_25_34: 32, age_35_44: 8, age_45_plus: 2, female: 67, male: 33, top_countries: ['US', 'JP', 'UK'] },
    categories: ['fashion', 'photography', 'streetstyle'], past_brand_deals: ['fashion', 'accessories', 'photography'],
    estimated_cpm: 6, estimated_rate_per_post: 1600, contact_email: 'monica@streetstyle.com',
    location: 'New York, USA', brand_safety_score: 94, fake_follower_percentage: 4.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Stopped strangers to rate outfits 😱', 'NYC Fashion Week street style', 'Best dressed people I saw this week', 'What people actually wear in Tokyo', 'Street style: expensive vs affordable']
  },
  {
    id: 'mock-35', external_id: 'tt-15', handle: 'coffeechat_olivia', full_name: 'Olivia Reed',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@coffeechat_olivia',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=olivia',
    bio: 'Coffee content creator ☕ Home barista. Cafe hopping. Life with caffeine.',
    follower_count: 290000, engagement_rate: 7.6, avg_likes: 22040, avg_comments: 1080, avg_views: 420000,
    audience_demographics: { age_18_24: 50, age_25_34: 40, age_35_44: 8, age_45_plus: 2, female: 62, male: 38, top_countries: ['US', 'UK', 'AU'] },
    categories: ['coffee', 'food', 'lifestyle'], past_brand_deals: ['coffee', 'food', 'lifestyle'],
    estimated_cpm: 6, estimated_rate_per_post: 2400, contact_email: 'olivia@coffeechat.com',
    location: 'Portland, USA', brand_safety_score: 96, fake_follower_percentage: 3.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['Making a $8 latte at home for $0.80', 'Ranking every coffee drink', 'My home espresso setup tour', 'Best coffee shops I\'ve visited', 'Can I recreate a Starbucks menu?']
  },
  // YouTube Tech Reviews/Fitness/Cooking (15)
  {
    id: 'mock-36', external_id: 'yt-1', handle: 'techwithjames', full_name: 'James Liu',
    platform: 'YouTube', profile_url: 'https://youtube.com/@techwithjames',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=james',
    bio: 'Honest tech reviews. No fluff. Helping you spend your money wisely.',
    follower_count: 780000, engagement_rate: 4.2, avg_likes: 32760, avg_comments: 1820, avg_views: 280000,
    audience_demographics: { age_18_24: 38, age_25_34: 44, age_35_44: 14, age_45_plus: 4, female: 28, male: 72, top_countries: ['US', 'UK', 'IN'] },
    categories: ['tech', 'reviews', 'gadgets'], past_brand_deals: ['tech', 'software', 'electronics'],
    estimated_cpm: 8, estimated_rate_per_post: 7200, contact_email: 'james@techwithjames.com',
    location: 'San Jose, USA', brand_safety_score: 94, fake_follower_percentage: 3.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['I bought every iPhone 15 model — here\'s the truth', 'Is this $500 laptop worth it?', 'Best tech under $100 (I tested them all)', 'Stop buying expensive cables', '3 months with the Apple Watch Ultra']
  },
  {
    id: 'mock-37', external_id: 'yt-2', handle: 'fitnessfueled_dan', full_name: 'Dan Mitchell',
    platform: 'YouTube', profile_url: 'https://youtube.com/@fitnessfueled_dan',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=dan',
    bio: 'Fitness coach & content creator. Evidence-based. No bro science.',
    follower_count: 1100000, engagement_rate: 3.8, avg_likes: 41800, avg_comments: 2200, avg_views: 420000,
    audience_demographics: { age_18_24: 40, age_25_34: 45, age_35_44: 12, age_45_plus: 3, female: 38, male: 62, top_countries: ['US', 'UK', 'CA'] },
    categories: ['fitness', 'health', 'nutrition'], past_brand_deals: ['fitness', 'supplements', 'clothing', 'tech'],
    estimated_cpm: 6, estimated_rate_per_post: 9500, contact_email: 'dan@fitnessfueled.com',
    location: 'Denver, USA', brand_safety_score: 95, fake_follower_percentage: 4.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Full body workout that actually builds muscle', 'Protein myths debunked by science', 'I tried every fitness tracker for 6 months', 'What I eat in a day as a coach', 'Home gym setup under $500']
  },
  {
    id: 'mock-38', external_id: 'yt-3', handle: 'fromthekitchentable', full_name: 'Elena Rossi',
    platform: 'YouTube', profile_url: 'https://youtube.com/@fromthekitchentable',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=elena',
    bio: 'Italian-American home cooking. Nonna\'s recipes, modern twists.',
    follower_count: 650000, engagement_rate: 4.5, avg_likes: 29250, avg_comments: 1580, avg_views: 240000,
    audience_demographics: { age_18_24: 25, age_25_34: 42, age_35_44: 24, age_45_plus: 9, female: 65, male: 35, top_countries: ['US', 'IT', 'CA'] },
    categories: ['cooking', 'italian', 'food'], past_brand_deals: ['food', 'cooking', 'beverages', 'kitchen'],
    estimated_cpm: 9, estimated_rate_per_post: 7000, contact_email: 'elena@kitchentable.com',
    location: 'Boston, USA', brand_safety_score: 97, fake_follower_percentage: 2.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Nonna\'s carbonara recipe (the real one)', 'Sunday sauce from scratch', 'Making pasta for the first time: tips I wish I knew', 'Italian pantry staples you need', '1 hour Italian dinner party menu']
  },
  {
    id: 'mock-39', external_id: 'yt-4', handle: 'gadget_guru_alex', full_name: 'Alex Pham',
    platform: 'YouTube', profile_url: 'https://youtube.com/@gadget_guru_alex',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=alexp',
    bio: 'Reviewing the latest tech so you don\'t have to. Singapore-based.',
    follower_count: 420000, engagement_rate: 3.9, avg_likes: 16380, avg_comments: 920, avg_views: 160000,
    audience_demographics: { age_18_24: 42, age_25_34: 40, age_35_44: 14, age_45_plus: 4, female: 22, male: 78, top_countries: ['SG', 'US', 'IN'] },
    categories: ['tech', 'gadgets', 'reviews'], past_brand_deals: ['tech', 'electronics', 'software'],
    estimated_cpm: 10, estimated_rate_per_post: 5200, contact_email: 'alex@gadgetguru.sg',
    location: 'Singapore', brand_safety_score: 93, fake_follower_percentage: 4.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['Samsung vs Apple — who wins in 2024?', 'Best budget smartphones of the year', 'I bought every flagship phone', 'Tech accessories worth every cent', 'Laptop buying guide 2024']
  },
  {
    id: 'mock-40', external_id: 'yt-5', handle: 'strengthcoach_kate', full_name: 'Kate Sullivan',
    platform: 'YouTube', profile_url: 'https://youtube.com/@strengthcoach_kate',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=kate',
    bio: 'Strength coach. Powerlifter. Making women stronger & more confident.',
    follower_count: 380000, engagement_rate: 4.8, avg_likes: 18240, avg_comments: 980, avg_views: 145000,
    audience_demographics: { age_18_24: 35, age_25_34: 48, age_35_44: 14, age_45_plus: 3, female: 80, male: 20, top_countries: ['US', 'UK', 'AU'] },
    categories: ['fitness', 'strength', 'wellness'], past_brand_deals: ['fitness', 'supplements', 'clothing'],
    estimated_cpm: 11, estimated_rate_per_post: 5400, contact_email: 'kate@strengthcoach.com',
    location: 'Austin, USA', brand_safety_score: 96, fake_follower_percentage: 3.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['How I went from couch to deadlifting 200lbs', 'Women & heavy lifting: what you need to know', 'My current training program', 'Supplements I actually take (and why)', '12-week body transformation update']
  },
  {
    id: 'mock-41', external_id: 'yt-6', handle: 'thecookingscientist', full_name: 'Dr. Sarah Chen',
    platform: 'YouTube', profile_url: 'https://youtube.com/@thecookingscientist',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=sarahc',
    bio: 'Food scientist turned YouTuber. The science behind cooking. Demystifying food.',
    follower_count: 520000, engagement_rate: 4.2, avg_likes: 21840, avg_comments: 1240, avg_views: 195000,
    audience_demographics: { age_18_24: 30, age_25_34: 45, age_35_44: 18, age_45_plus: 7, female: 55, male: 45, top_countries: ['US', 'UK', 'CA'] },
    categories: ['cooking', 'science', 'food'], past_brand_deals: ['food', 'cooking', 'education'],
    estimated_cpm: 9, estimated_rate_per_post: 6200, contact_email: 'sarah@cookingscientist.com',
    location: 'Chicago, USA', brand_safety_score: 98, fake_follower_percentage: 2.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Why your bread rises (and why it doesn\'t)', 'The science of caramelization', 'Gluten explained simply', 'Why restaurant food tastes better', 'Food additives: fear vs facts']
  },
  {
    id: 'mock-42', external_id: 'yt-7', handle: 'mobiletechreviews', full_name: 'Ryan Walsh',
    platform: 'YouTube', profile_url: 'https://youtube.com/@mobiletechreviews',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=ryan',
    bio: 'Mobile tech enthusiast. Smartphones, wearables, and everything connected.',
    follower_count: 1450000, engagement_rate: 2.9, avg_likes: 42050, avg_comments: 2420, avg_views: 580000,
    audience_demographics: { age_18_24: 42, age_25_34: 42, age_35_44: 12, age_45_plus: 4, female: 25, male: 75, top_countries: ['US', 'UK', 'IN'] },
    categories: ['tech', 'mobile', 'reviews'], past_brand_deals: ['tech', 'electronics', 'apps'],
    estimated_cpm: 5, estimated_rate_per_post: 10200, contact_email: 'ryan@mobiletechreviews.com',
    location: 'Seattle, USA', brand_safety_score: 91, fake_follower_percentage: 5.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Galaxy S24 Ultra: 6 months later', 'Every phone under $400 ranked', 'The phone I\'d actually buy (not sponsored)', 'Hidden features in iOS 17', 'Best smartphone cameras tested']
  },
  {
    id: 'mock-43', external_id: 'yt-8', handle: 'plantbasedpete', full_name: 'Pete Morrison',
    platform: 'YouTube', profile_url: 'https://youtube.com/@plantbasedpete',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=pete',
    bio: 'Former carnivore, now plant-based athlete. Recipes, workouts, life.',
    follower_count: 290000, engagement_rate: 5.1, avg_likes: 14790, avg_comments: 820, avg_views: 108000,
    audience_demographics: { age_18_24: 32, age_25_34: 46, age_35_44: 16, age_45_plus: 6, female: 48, male: 52, top_countries: ['US', 'UK', 'AU'] },
    categories: ['fitness', 'vegan', 'cooking'], past_brand_deals: ['food', 'fitness', 'wellness'],
    estimated_cpm: 10, estimated_rate_per_post: 3800, contact_email: 'pete@plantbasedpete.com',
    location: 'Vancouver, Canada', brand_safety_score: 96, fake_follower_percentage: 3.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['I ate vegan for 90 days and got stronger', 'Plant-based protein for athletes', 'Meal prep for marathon training', 'Building muscle on plants: my journey', '7 day vegan meal plan for bulking']
  },
  {
    id: 'mock-44', external_id: 'yt-9', handle: 'homecookingschool', full_name: 'Chef Antonio',
    platform: 'YouTube', profile_url: 'https://youtube.com/@homecookingschool',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=antonio',
    bio: 'Professional chef teaching home cooks. Every skill you need, step by step.',
    follower_count: 870000, engagement_rate: 3.6, avg_likes: 31320, avg_comments: 1780, avg_views: 320000,
    audience_demographics: { age_18_24: 28, age_25_34: 40, age_35_44: 24, age_45_plus: 8, female: 60, male: 40, top_countries: ['US', 'UK', 'AU'] },
    categories: ['cooking', 'education', 'food'], past_brand_deals: ['food', 'cooking', 'kitchen', 'beverages'],
    estimated_cpm: 7, estimated_rate_per_post: 8200, contact_email: 'antonio@homecookingschool.com',
    location: 'New York, USA', brand_safety_score: 97, fake_follower_percentage: 3.4,
    last_updated: new Date().toISOString(),
    sample_captions: ['5 knife skills every home cook needs', 'How to make the perfect steak', 'Classic French techniques simplified', 'Meal planning for beginners', 'How to season food properly']
  },
  {
    id: 'mock-45', external_id: 'yt-10', handle: 'yogawithlena', full_name: 'Lena Berg',
    platform: 'YouTube', profile_url: 'https://youtube.com/@yogawithlena',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=lena',
    bio: 'Yoga teacher & wellness creator. Making yoga accessible for everyone.',
    follower_count: 740000, engagement_rate: 4.1, avg_likes: 30340, avg_comments: 1620, avg_views: 270000,
    audience_demographics: { age_18_24: 30, age_25_34: 45, age_35_44: 18, age_45_plus: 7, female: 84, male: 16, top_countries: ['US', 'UK', 'DE'] },
    categories: ['yoga', 'wellness', 'fitness'], past_brand_deals: ['wellness', 'fitness', 'lifestyle', 'clothing'],
    estimated_cpm: 8, estimated_rate_per_post: 7800, contact_email: 'lena@yogawithlena.com',
    location: 'Amsterdam, Netherlands', brand_safety_score: 98, fake_follower_percentage: 2.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['30 min morning yoga for energy', 'Yoga for anxiety: what actually helps', 'Beginner yoga mistakes I made', 'Full body stretch with no equipment', 'Yin yoga for deep relaxation']
  },
  {
    id: 'mock-46', external_id: 'yt-11', handle: 'techunboxed_raj', full_name: 'Raj Patel',
    platform: 'YouTube', profile_url: 'https://youtube.com/@techunboxed_raj',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=raj',
    bio: 'Tech unboxing & reviews. Gadget enthusiast. Mumbai-based creator.',
    follower_count: 560000, engagement_rate: 3.5, avg_likes: 19600, avg_comments: 1120, avg_views: 210000,
    audience_demographics: { age_18_24: 45, age_25_34: 40, age_35_44: 12, age_45_plus: 3, female: 20, male: 80, top_countries: ['IN', 'US', 'UK'] },
    categories: ['tech', 'unboxing', 'gadgets'], past_brand_deals: ['tech', 'electronics', 'software'],
    estimated_cpm: 9, estimated_rate_per_post: 6400, contact_email: 'raj@techunboxed.in',
    location: 'Mumbai, India', brand_safety_score: 92, fake_follower_percentage: 4.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['iPhone 15 Pro unboxing & first look', 'Best budget laptops for students in India', 'Unboxing the most expensive phone ever', 'Tech I bought from Amazon vs Flipkart', 'Should you upgrade in 2024?']
  },
  {
    id: 'mock-47', external_id: 'yt-12', handle: 'runningwithrachel', full_name: 'Rachel Owens',
    platform: 'YouTube', profile_url: 'https://youtube.com/@runningwithrachel',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=rachel',
    bio: 'Marathon runner, running coach & nutrition nerd. Making running accessible.',
    follower_count: 320000, engagement_rate: 4.9, avg_likes: 15680, avg_comments: 840, avg_views: 120000,
    audience_demographics: { age_18_24: 28, age_25_34: 48, age_35_44: 18, age_45_plus: 6, female: 72, male: 28, top_countries: ['US', 'UK', 'AU'] },
    categories: ['running', 'fitness', 'nutrition'], past_brand_deals: ['fitness', 'footwear', 'nutrition'],
    estimated_cpm: 11, estimated_rate_per_post: 4600, contact_email: 'rachel@runningwithrachel.com',
    location: 'Boston, USA', brand_safety_score: 97, fake_follower_percentage: 2.6,
    last_updated: new Date().toISOString(),
    sample_captions: ['How I qualified for Boston Marathon', 'Running nutrition guide for beginners', 'Shoes I\'ve run 500+ miles in', 'Training for my first marathon (again)', 'Why I love (and hate) running']
  },
  {
    id: 'mock-48', external_id: 'yt-13', handle: 'bakingwitbeth', full_name: 'Beth Anderson',
    platform: 'YouTube', profile_url: 'https://youtube.com/@bakingwithbeth',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=beth',
    bio: 'Baking made approachable. Beginner-friendly recipes & techniques.',
    follower_count: 480000, engagement_rate: 4.4, avg_likes: 21120, avg_comments: 1160, avg_views: 180000,
    audience_demographics: { age_18_24: 28, age_25_34: 42, age_35_44: 22, age_45_plus: 8, female: 76, male: 24, top_countries: ['US', 'UK', 'CA'] },
    categories: ['baking', 'cooking', 'food'], past_brand_deals: ['food', 'baking', 'kitchen'],
    estimated_cpm: 9, estimated_rate_per_post: 5800, contact_email: 'beth@bakingwithbeth.com',
    location: 'Nashville, USA', brand_safety_score: 98, fake_follower_percentage: 2.3,
    last_updated: new Date().toISOString(),
    sample_captions: ['The perfect chocolate chip cookie (finally!)', 'Bread baking for absolute beginners', 'French pastry at home: croissants', 'No-knead bread you\'ll make every week', 'Why your cake is sinking (and how to fix it)']
  },
  {
    id: 'mock-49', external_id: 'yt-14', handle: 'techminimalist_finn', full_name: 'Finn Clarke',
    platform: 'YouTube', profile_url: 'https://youtube.com/@techminimalist_finn',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=finn',
    bio: 'Minimal tech setup. Digital minimalism. Productivity without the noise.',
    follower_count: 240000, engagement_rate: 5.2, avg_likes: 12480, avg_comments: 680, avg_views: 90000,
    audience_demographics: { age_18_24: 35, age_25_34: 48, age_35_44: 14, age_45_plus: 3, female: 32, male: 68, top_countries: ['US', 'UK', 'DE'] },
    categories: ['tech', 'productivity', 'minimalism'], past_brand_deals: ['tech', 'apps', 'productivity'],
    estimated_cpm: 12, estimated_rate_per_post: 3800, contact_email: 'finn@techminimalist.com',
    location: 'Berlin, Germany', brand_safety_score: 96, fake_follower_percentage: 3.0,
    last_updated: new Date().toISOString(),
    sample_captions: ['My minimal desk setup 2024', 'Apps I deleted and why', 'Digital detox: one month update', 'The only apps you actually need', 'Why I switched to a dumb phone (temporarily)']
  },
  {
    id: 'mock-50', external_id: 'yt-15', handle: 'globalcuisine_mei', full_name: 'Mei Zhou',
    platform: 'YouTube', profile_url: 'https://youtube.com/@globalcuisine_mei',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=mei',
    bio: 'Authentic global recipes from my kitchen. 30+ cuisines and counting.',
    follower_count: 720000, engagement_rate: 4.0, avg_likes: 28800, avg_comments: 1560, avg_views: 265000,
    audience_demographics: { age_18_24: 30, age_25_34: 44, age_35_44: 20, age_45_plus: 6, female: 62, male: 38, top_countries: ['US', 'CA', 'AU'] },
    categories: ['cooking', 'multicultural', 'food'], past_brand_deals: ['food', 'cooking', 'travel', 'kitchen'],
    estimated_cpm: 8, estimated_rate_per_post: 7500, contact_email: 'mei@globalcuisine.com',
    location: 'San Francisco, USA', brand_safety_score: 97, fake_follower_percentage: 3.3,
    last_updated: new Date().toISOString(),
    sample_captions: ['Authentic dim sum at home', 'The dish that got me into cooking', 'Chinese New Year feast from scratch', '5 cuisines in 5 days challenge', 'Street food from my grandmother\'s village']
  },
  // Instagram Fitness (10)
  {
    id: 'mock-51', external_id: 'ig-f1', handle: 'trainwithtom', full_name: 'Tom Bradley',
    platform: 'Instagram', profile_url: 'https://instagram.com/trainwithtom',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=tom',
    bio: 'NASM-certified PT. Helping regular people get extraordinary results.',
    follower_count: 185000, engagement_rate: 3.8, avg_likes: 7030, avg_comments: 358, avg_views: 26000,
    audience_demographics: { age_18_24: 36, age_25_34: 48, age_35_44: 13, age_45_plus: 3, female: 45, male: 55, top_countries: ['US', 'UK', 'AU'] },
    categories: ['fitness', 'training', 'nutrition'], past_brand_deals: ['fitness', 'supplements', 'clothing'],
    estimated_cpm: 11, estimated_rate_per_post: 2400, contact_email: 'tom@trainwithtom.com',
    location: 'Phoenix, USA', brand_safety_score: 94, fake_follower_percentage: 4.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Beginner workout program (free) 📋', 'Compound exercises every gym-goer needs', 'My client lost 40lbs in 6 months — here\'s how', 'Gym mistakes I see daily', 'Building muscle after 30']
  },
  {
    id: 'mock-52', external_id: 'ig-f2', handle: 'yogavibes_hannah', full_name: 'Hannah Price',
    platform: 'Instagram', profile_url: 'https://instagram.com/yogavibes_hannah',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=hannah',
    bio: 'Yoga teacher. Wellness advocate. Making movement joyful. Bristol, UK.',
    follower_count: 92000, engagement_rate: 5.1, avg_likes: 4692, avg_comments: 238, avg_views: 13000,
    audience_demographics: { age_18_24: 32, age_25_34: 48, age_35_44: 16, age_45_plus: 4, female: 86, male: 14, top_countries: ['UK', 'US', 'AU'] },
    categories: ['yoga', 'wellness', 'mindfulness'], past_brand_deals: ['wellness', 'fitness', 'lifestyle'],
    estimated_cpm: 13, estimated_rate_per_post: 1500, contact_email: 'hannah@yogavibes.co.uk',
    location: 'Bristol, UK', brand_safety_score: 98, fake_follower_percentage: 2.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['Morning yoga flow 🌅', 'Yoga poses for back pain relief', 'My journey to splits (6 months progress)', 'Breathwork for anxiety', 'Full moon yin yoga sequence']
  },
  {
    id: 'mock-53', external_id: 'ig-f3', handle: 'liftlikelila', full_name: 'Lila Chen',
    platform: 'Instagram', profile_url: 'https://instagram.com/liftlikelila',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=lila',
    bio: 'Powerlifter. Strength coach. Asian-American. Normalizing women lifting heavy.',
    follower_count: 134000, engagement_rate: 4.6, avg_likes: 6164, avg_comments: 310, avg_views: 19000,
    audience_demographics: { age_18_24: 38, age_25_34: 48, age_35_44: 11, age_45_plus: 3, female: 82, male: 18, top_countries: ['US', 'CA', 'UK'] },
    categories: ['powerlifting', 'fitness', 'strength'], past_brand_deals: ['fitness', 'clothing', 'supplements'],
    estimated_cpm: 12, estimated_rate_per_post: 1900, contact_email: 'lila@liftlikelila.com',
    location: 'San Diego, USA', brand_safety_score: 96, fake_follower_percentage: 2.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['First 200kg deadlift 💪', 'Training split for powerlifting', 'What I eat on competition day', 'My mental health journey through sport', 'Overcoming injury: 6 month update']
  },
  {
    id: 'mock-54', external_id: 'ig-f4', handle: 'crossfit_coach_mike', full_name: 'Mike Torres',
    platform: 'Instagram', profile_url: 'https://instagram.com/crossfit_coach_mike',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=mike',
    bio: 'CrossFit L2 Coach. Competition prep. WODs, nutrition, community.',
    follower_count: 78000, engagement_rate: 4.9, avg_likes: 3822, avg_comments: 195, avg_views: 11000,
    audience_demographics: { age_18_24: 34, age_25_34: 50, age_35_44: 13, age_45_plus: 3, female: 40, male: 60, top_countries: ['US', 'CA', 'AU'] },
    categories: ['crossfit', 'fitness', 'nutrition'], past_brand_deals: ['fitness', 'supplements', 'clothing'],
    estimated_cpm: 14, estimated_rate_per_post: 1300, contact_email: 'mike@crossfitcoach.com',
    location: 'Denver, USA', brand_safety_score: 93, fake_follower_percentage: 3.6,
    last_updated: new Date().toISOString(),
    sample_captions: ['WOD Wednesday: benchmark workout', 'How to scale CrossFit for beginners', 'Competition week nutrition protocol', 'My CrossFit Games experience', 'Building gymnastics skills from zero']
  },
  {
    id: 'mock-55', external_id: 'ig-f5', handle: 'bikinifit_nina', full_name: 'Nina Fox',
    platform: 'Instagram', profile_url: 'https://instagram.com/bikinifit_nina',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=nina',
    bio: 'IFBB Bikini Pro. Coach. Helping women compete & love their bodies.',
    follower_count: 220000, engagement_rate: 3.5, avg_likes: 7700, avg_comments: 390, avg_views: 31000,
    audience_demographics: { age_18_24: 36, age_25_34: 48, age_35_44: 13, age_45_plus: 3, female: 90, male: 10, top_countries: ['US', 'AU', 'CA'] },
    categories: ['bikini', 'fitness', 'competition'], past_brand_deals: ['fitness', 'supplements', 'clothing', 'nutrition'],
    estimated_cpm: 10, estimated_rate_per_post: 2800, contact_email: 'nina@bikinifit.com',
    location: 'Las Vegas, USA', brand_safety_score: 88, fake_follower_percentage: 5.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['My competition prep diet (full breakdown)', 'Peak week transformations 🏆', 'What judges look for in bikini division', 'Off-season bulk: what I\'m eating', 'My first show vs. now']
  },
  {
    id: 'mock-56', external_id: 'ig-f6', handle: 'everydayfitness_jo', full_name: 'Jo Richardson',
    platform: 'Instagram', profile_url: 'https://instagram.com/everydayfitness_jo',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=jo',
    bio: 'Making fitness fit your life. No gym needed. Real talk about health.',
    follower_count: 48000, engagement_rate: 6.8, avg_likes: 3264, avg_comments: 166, avg_views: 6800,
    audience_demographics: { age_18_24: 32, age_25_34: 46, age_35_44: 18, age_45_plus: 4, female: 78, male: 22, top_countries: ['UK', 'US', 'CA'] },
    categories: ['fitness', 'lifestyle', 'home-workout'], past_brand_deals: ['fitness', 'wellness', 'clothing'],
    estimated_cpm: 15, estimated_rate_per_post: 880, contact_email: 'jo@everydayfitness.co.uk',
    location: 'Edinburgh, UK', brand_safety_score: 97, fake_follower_percentage: 2.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['30 min workout you can do anywhere', 'Why I quit the gym (and got fitter)', 'Realistic fitness for busy people', 'Walking: underrated fitness tool', 'What getting fit at 40 looks like']
  },
  {
    id: 'mock-57', external_id: 'ig-f7', handle: 'swimmerfitjess', full_name: 'Jessica Aquino',
    platform: 'Instagram', profile_url: 'https://instagram.com/swimmerfitjess',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=jess',
    bio: 'Former competitive swimmer. Fitness & swim content. Healthy lifestyle.',
    follower_count: 62000, engagement_rate: 5.4, avg_likes: 3348, avg_comments: 170, avg_views: 8800,
    audience_demographics: { age_18_24: 38, age_25_34: 44, age_35_44: 14, age_45_plus: 4, female: 65, male: 35, top_countries: ['US', 'AU', 'CA'] },
    categories: ['swimming', 'fitness', 'wellness'], past_brand_deals: ['swimwear', 'fitness', 'nutrition'],
    estimated_cpm: 14, estimated_rate_per_post: 1050, contact_email: 'jess@swimmerfitjess.com',
    location: 'Miami, USA', brand_safety_score: 96, fake_follower_percentage: 2.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['Open water swimming guide for beginners', 'Dryland training for swimmers', 'My swimwear collection review', 'Lane etiquette at public pools', 'Cold water therapy: my experience']
  },
  {
    id: 'mock-58', external_id: 'ig-f8', handle: 'boxingmom_claire', full_name: 'Claire Burke',
    platform: 'Instagram', profile_url: 'https://instagram.com/boxingmom_claire',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=claire',
    bio: 'Boxing coach. Mom of two. Hitting things for stress relief since 2015.',
    follower_count: 41000, engagement_rate: 7.1, avg_likes: 2911, avg_comments: 148, avg_views: 5900,
    audience_demographics: { age_18_24: 28, age_25_34: 48, age_35_44: 20, age_45_plus: 4, female: 74, male: 26, top_countries: ['US', 'UK', 'IE'] },
    categories: ['boxing', 'fitness', 'lifestyle'], past_brand_deals: ['fitness', 'clothing', 'wellness'],
    estimated_cpm: 16, estimated_rate_per_post: 780, contact_email: 'claire@boxingmom.com',
    location: 'Dublin, Ireland', brand_safety_score: 95, fake_follower_percentage: 2.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Mom & baby boxing workout 🥊', 'How I got back into fitness postpartum', 'Beginner boxing: where to start', 'Why boxing is the best stress relief', 'My boxing gear essentials']
  },
  {
    id: 'mock-59', external_id: 'ig-f9', handle: 'triathlonted', full_name: 'Ted Morrison',
    platform: 'Instagram', profile_url: 'https://instagram.com/triathlonted',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=ted',
    bio: 'Amateur triathlete. Juggling work, family, and Ironman training.',
    follower_count: 29000, engagement_rate: 8.4, avg_likes: 2436, avg_comments: 124, avg_views: 4100,
    audience_demographics: { age_18_24: 18, age_25_34: 42, age_35_44: 32, age_45_plus: 8, female: 35, male: 65, top_countries: ['US', 'UK', 'DE'] },
    categories: ['triathlon', 'fitness', 'nutrition'], past_brand_deals: ['fitness', 'nutrition', 'tech'],
    estimated_cpm: 17, estimated_rate_per_post: 620, contact_email: 'ted@triathlonted.com',
    location: 'Chicago, USA', brand_safety_score: 97, fake_follower_percentage: 1.9,
    last_updated: new Date().toISOString(),
    sample_captions: ['My first Ironman race report', 'How to train for triathlon with a full-time job', 'Nutrition strategy for race day', 'Best triathlon gear under $500', 'Off-season training block']
  },
  {
    id: 'mock-60', external_id: 'ig-f10', handle: 'hyrox_hunter', full_name: 'Hunter Davis',
    platform: 'Instagram', profile_url: 'https://instagram.com/hyrox_hunter',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=hunter',
    bio: 'HYROX athlete & coach. Functional fitness. Competing globally.',
    follower_count: 55000, engagement_rate: 6.2, avg_likes: 3410, avg_comments: 172, avg_views: 7800,
    audience_demographics: { age_18_24: 32, age_25_34: 52, age_35_44: 14, age_45_plus: 2, female: 42, male: 58, top_countries: ['US', 'UK', 'DE'] },
    categories: ['hyrox', 'functional-fitness', 'endurance'], past_brand_deals: ['fitness', 'nutrition', 'clothing'],
    estimated_cpm: 14, estimated_rate_per_post: 950, contact_email: 'hunter@hyroxhunter.com',
    location: 'London, UK', brand_safety_score: 94, fake_follower_percentage: 3.1,
    last_updated: new Date().toISOString(),
    sample_captions: ['HYROX World Championships recap 🏆', 'My 12-week HYROX training plan', 'What to eat before HYROX', 'Common HYROX mistakes beginners make', 'HYROX doubles with my partner']
  },
  // TikTok/Instagram Gaming (10)
  {
    id: 'mock-61', external_id: 'tt-g1', handle: 'gamer_galaxy_jay', full_name: 'Jay Kim',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@gamer_galaxy_jay',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=jay',
    bio: 'Gaming content creator. FPS pro. Fortnite, Valorant & more.',
    follower_count: 920000, engagement_rate: 7.8, avg_likes: 71760, avg_comments: 3480, avg_views: 1400000,
    audience_demographics: { age_18_24: 58, age_25_34: 30, age_35_44: 9, age_45_plus: 3, female: 28, male: 72, top_countries: ['US', 'UK', 'CA'] },
    categories: ['gaming', 'fps', 'esports'], past_brand_deals: ['gaming', 'tech', 'energy drinks'],
    estimated_cpm: 4, estimated_rate_per_post: 6800, contact_email: 'jay@gamergalaxy.com',
    location: 'Los Angeles, USA', brand_safety_score: 86, fake_follower_percentage: 8.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Carrying my team solo 😤', 'Ranked to top 100 in 30 days', 'Settings that pros actually use', 'Most satisfying clips of the month', 'Reacting to my worst plays ever']
  },
  {
    id: 'mock-62', external_id: 'ig-g1', handle: 'retrogaming_rex', full_name: 'Rex Martin',
    platform: 'Instagram', profile_url: 'https://instagram.com/retrogaming_rex',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=rex',
    bio: 'Retro game collector & content creator. Nostalgia dealer.',
    follower_count: 68000, engagement_rate: 5.6, avg_likes: 3808, avg_comments: 194, avg_views: 9600,
    audience_demographics: { age_18_24: 28, age_25_34: 42, age_35_44: 24, age_45_plus: 6, female: 25, male: 75, top_countries: ['US', 'UK', 'JP'] },
    categories: ['retro-gaming', 'collecting', 'tech'], past_brand_deals: ['gaming', 'tech', 'accessories'],
    estimated_cpm: 13, estimated_rate_per_post: 1100, contact_email: 'rex@retrogamingrex.com',
    location: 'Portland, USA', brand_safety_score: 93, fake_follower_percentage: 3.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Found this at a garage sale for $2 🕹️', 'My retro game collection tour', 'Most valuable games I own', 'Thrift gaming haul (rare finds!)', 'Playing games I loved as a kid']
  },
  {
    id: 'mock-63', external_id: 'tt-g2', handle: 'mobilegaming_quinn', full_name: 'Quinn Foster',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@mobilegaming_quinn',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=quinn',
    bio: 'Mobile gaming content. Top rankings. Honest game reviews.',
    follower_count: 480000, engagement_rate: 8.5, avg_likes: 40800, avg_comments: 1960, avg_views: 680000,
    audience_demographics: { age_18_24: 52, age_25_34: 36, age_35_44: 10, age_45_plus: 2, female: 38, male: 62, top_countries: ['US', 'PH', 'IN'] },
    categories: ['mobile-gaming', 'gaming', 'reviews'], past_brand_deals: ['gaming', 'tech', 'apps'],
    estimated_cpm: 5, estimated_rate_per_post: 3600, contact_email: 'quinn@mobilegaming.com',
    location: 'Phoenix, USA', brand_safety_score: 89, fake_follower_percentage: 6.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Top mobile games free-to-play 2024', 'Is it pay-to-win? Honest review', 'My global ranking journey', 'Best phone for mobile gaming', 'Scam vs legit: free game test']
  },
  {
    id: 'mock-64', external_id: 'ig-g2', handle: 'nintendofan_nat', full_name: 'Natalie Cross',
    platform: 'Instagram', profile_url: 'https://instagram.com/nintendofan_nat',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=nat',
    bio: 'Nintendo super-fan. Cozy games, Animal Crossing & everything Nintendo.',
    follower_count: 125000, engagement_rate: 4.8, avg_likes: 6000, avg_comments: 305, avg_views: 17800,
    audience_demographics: { age_18_24: 40, age_25_34: 44, age_35_44: 12, age_45_plus: 4, female: 65, male: 35, top_countries: ['US', 'JP', 'UK'] },
    categories: ['nintendo', 'cozy-gaming', 'lifestyle'], past_brand_deals: ['gaming', 'tech', 'lifestyle'],
    estimated_cpm: 12, estimated_rate_per_post: 1800, contact_email: 'nat@nintendofannat.com',
    location: 'Seattle, USA', brand_safety_score: 97, fake_follower_percentage: 2.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['My dream Animal Crossing island 🌴', 'Every Nintendo Switch game ranked', 'Cozy games for anxious days', 'Unboxing limited edition Switch', 'What I wish Nintendo would make']
  },
  {
    id: 'mock-65', external_id: 'tt-g3', handle: 'esports_eli', full_name: 'Eli Zhang',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@esports_eli',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=eli',
    bio: 'Pro esports player & content creator. League of Legends main.',
    follower_count: 680000, engagement_rate: 7.2, avg_likes: 48960, avg_comments: 2380, avg_views: 980000,
    audience_demographics: { age_18_24: 60, age_25_34: 32, age_35_44: 7, age_45_plus: 1, female: 22, male: 78, top_countries: ['US', 'KR', 'CN'] },
    categories: ['esports', 'gaming', 'lifestyle'], past_brand_deals: ['gaming', 'tech', 'energy drinks'],
    estimated_cpm: 4, estimated_rate_per_post: 5200, contact_email: 'eli@esporteli.com',
    location: 'Los Angeles, USA', brand_safety_score: 85, fake_follower_percentage: 7.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Day in life of a pro gamer', 'Scrims at 3am: worth it?', 'My training regime for worlds', 'What I eat during tournament week', 'Reacting to my worst performance ever']
  },
  {
    id: 'mock-66', external_id: 'ig-g3', handle: 'rpg_queen_diana', full_name: 'Diana Stone',
    platform: 'Instagram', profile_url: 'https://instagram.com/rpg_queen_diana',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=diana',
    bio: 'RPG enthusiast. Fantasy art & gaming. Book + game crossovers.',
    follower_count: 54000, engagement_rate: 6.4, avg_likes: 3456, avg_comments: 176, avg_views: 7700,
    audience_demographics: { age_18_24: 38, age_25_34: 46, age_35_44: 14, age_45_plus: 2, female: 62, male: 38, top_countries: ['US', 'UK', 'CA'] },
    categories: ['rpg', 'fantasy', 'gaming'], past_brand_deals: ['gaming', 'books', 'accessories'],
    estimated_cpm: 14, estimated_rate_per_post: 950, contact_email: 'diana@rpgqueen.com',
    location: 'Austin, USA', brand_safety_score: 94, fake_follower_percentage: 3.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Most anticipated RPGs of 2024 🗡️', 'Baldur\'s Gate 3: 200 hours in', 'Best RPG games for beginners', 'My fantasy gaming room setup', 'Why RPGs are the best genre (fight me)']
  },
  {
    id: 'mock-67', external_id: 'tt-g4', handle: 'speedrun_seb', full_name: 'Sebastian Flores',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@speedrun_seb',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=seb',
    bio: 'World record speedrunner. Breaking games since 2018.',
    follower_count: 1100000, engagement_rate: 9.4, avg_likes: 103400, avg_comments: 4800, avg_views: 1900000,
    audience_demographics: { age_18_24: 56, age_25_34: 34, age_35_44: 8, age_45_plus: 2, female: 25, male: 75, top_countries: ['US', 'UK', 'BR'] },
    categories: ['speedrunning', 'gaming', 'entertainment'], past_brand_deals: ['gaming', 'tech', 'energy drinks'],
    estimated_cpm: 3, estimated_rate_per_post: 7800, contact_email: 'seb@speedrunseb.com',
    location: 'Miami, USA', brand_safety_score: 88, fake_follower_percentage: 8.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['New world record 🏆 (by 3 milliseconds)', 'How speedrunning works explained', 'Most broken glitch in gaming history', 'Attempt #247 at my dream run', 'Games that are impossible to speedrun']
  },
  {
    id: 'mock-68', external_id: 'ig-g4', handle: 'gamergirl_ash', full_name: 'Ashley Ward',
    platform: 'Instagram', profile_url: 'https://instagram.com/gamergirl_ash',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=ash',
    bio: 'Gamer, cosplayer & content creator. PC gaming & streaming. Atlanta.',
    follower_count: 148000, engagement_rate: 4.2, avg_likes: 6216, avg_comments: 316, avg_views: 21000,
    audience_demographics: { age_18_24: 48, age_25_34: 38, age_35_44: 11, age_45_plus: 3, female: 58, male: 42, top_countries: ['US', 'UK', 'CA'] },
    categories: ['gaming', 'cosplay', 'lifestyle'], past_brand_deals: ['gaming', 'fashion', 'tech'],
    estimated_cpm: 11, estimated_rate_per_post: 2100, contact_email: 'ash@gamergirl.com',
    location: 'Atlanta, USA', brand_safety_score: 91, fake_follower_percentage: 5.0,
    last_updated: new Date().toISOString(),
    sample_captions: ['My gaming setup tour 🎮', 'Cosplay reveal: 3 months of work', 'What games I\'ve been playing', 'New gaming chair review', 'Stream highlights: funniest moments']
  },
  {
    id: 'mock-69', external_id: 'tt-g5', handle: 'indiegame_iris', full_name: 'Iris Chang',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@indiegame_iris',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=iris',
    bio: 'Indie game advocate. Showcasing hidden gems. Game dev student.',
    follower_count: 245000, engagement_rate: 9.8, avg_likes: 24010, avg_comments: 1140, avg_views: 360000,
    audience_demographics: { age_18_24: 54, age_25_34: 36, age_35_44: 8, age_45_plus: 2, female: 50, male: 50, top_countries: ['US', 'AU', 'UK'] },
    categories: ['indie-gaming', 'reviews', 'game-dev'], past_brand_deals: ['gaming', 'tech', 'software'],
    estimated_cpm: 6, estimated_rate_per_post: 2100, contact_email: 'iris@indiegameiris.com',
    location: 'Melbourne, Australia', brand_safety_score: 95, fake_follower_percentage: 3.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Indie game that made me cry 😭', '5 indie games you\'re sleeping on', 'Game dev diary: week 8 update', 'Hidden gems under $5 on Steam', 'This game was made by ONE person']
  },
  {
    id: 'mock-70', external_id: 'ig-g5', handle: 'virtualreality_vic', full_name: 'Victor Huang',
    platform: 'Instagram', profile_url: 'https://instagram.com/virtualreality_vic',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=vic',
    bio: 'VR enthusiast & content creator. Meta Quest 3 & beyond. The future is now.',
    follower_count: 38000, engagement_rate: 7.5, avg_likes: 2850, avg_comments: 145, avg_views: 5400,
    audience_demographics: { age_18_24: 40, age_25_34: 48, age_35_44: 10, age_45_plus: 2, female: 22, male: 78, top_countries: ['US', 'UK', 'DE'] },
    categories: ['vr', 'tech', 'gaming'], past_brand_deals: ['tech', 'gaming', 'fitness'],
    estimated_cpm: 16, estimated_rate_per_post: 720, contact_email: 'vic@vrwithvic.com',
    location: 'San Francisco, USA', brand_safety_score: 93, fake_follower_percentage: 2.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Meta Quest 3 vs PS VR2: honest comparison', 'VR workout that actually burns calories', 'Most immersive VR experiences 2024', 'I spent 24 hours in VR', 'Best VR games for beginners']
  },
  // Multi-platform Travel (10)
  {
    id: 'mock-71', external_id: 'multi-t1', handle: 'wanderlust_wei', full_name: 'Wei Zhang',
    platform: 'Instagram', profile_url: 'https://instagram.com/wanderlust_wei',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=wei',
    bio: 'Full-time traveler. 60+ countries. Photography & travel guides. Digital nomad.',
    follower_count: 580000, engagement_rate: 3.2, avg_likes: 18560, avg_comments: 945, avg_views: 82000,
    audience_demographics: { age_18_24: 32, age_25_34: 48, age_35_44: 16, age_45_plus: 4, female: 56, male: 44, top_countries: ['US', 'UK', 'AU'] },
    categories: ['travel', 'photography', 'digital-nomad'], past_brand_deals: ['travel', 'tech', 'fashion', 'accommodation'],
    estimated_cpm: 7, estimated_rate_per_post: 5400, contact_email: 'wei@wanderlustwei.com',
    location: 'Nomadic', brand_safety_score: 92, fake_follower_percentage: 5.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Why I moved to Bali for 6 months 🌴', '48 hours in Japan: where to go', 'How I afford to travel full time', 'Cheapest beautiful destinations in Europe', 'My camera gear for travel photography']
  },
  {
    id: 'mock-72', external_id: 'multi-t2', handle: 'solotraveler_sasha', full_name: 'Sasha Petrov',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@solotraveler_sasha',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=sasha',
    bio: 'Solo female traveler. Breaking stereotypes one trip at a time. 80+ countries.',
    follower_count: 840000, engagement_rate: 8.2, avg_likes: 68880, avg_comments: 3320, avg_views: 1250000,
    audience_demographics: { age_18_24: 45, age_25_34: 42, age_35_44: 10, age_45_plus: 3, female: 78, male: 22, top_countries: ['US', 'UK', 'CA'] },
    categories: ['solo-travel', 'adventure', 'safety'], past_brand_deals: ['travel', 'fashion', 'tech', 'beauty'],
    estimated_cpm: 4, estimated_rate_per_post: 6200, contact_email: 'sasha@solotraveler.com',
    location: 'Nomadic', brand_safety_score: 94, fake_follower_percentage: 6.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Solo female travel safety guide', 'I traveled to 10 countries alone this year', 'Most underrated solo destinations 2024', 'Things I wish I knew before solo travel', 'How locals treated me as a solo traveler']
  },
  {
    id: 'mock-73', external_id: 'multi-t3', handle: 'luxurytravel_leo', full_name: 'Leonardo Ferrari',
    platform: 'Instagram', profile_url: 'https://instagram.com/luxurytravel_leo',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=leonardof',
    bio: 'Luxury travel. 5-star hotels, private jets & bucket list experiences.',
    follower_count: 920000, engagement_rate: 2.4, avg_likes: 22080, avg_comments: 1104, avg_views: 130000,
    audience_demographics: { age_18_24: 22, age_25_34: 42, age_35_44: 28, age_45_plus: 8, female: 52, male: 48, top_countries: ['US', 'AE', 'UK'] },
    categories: ['luxury', 'travel', 'lifestyle'], past_brand_deals: ['luxury', 'travel', 'fashion', 'hospitality'],
    estimated_cpm: 6, estimated_rate_per_post: 8800, contact_email: 'leo@luxurytravelleo.com',
    location: 'Dubai, UAE', brand_safety_score: 89, fake_follower_percentage: 7.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Most expensive hotel in the world 🏨', 'Private island for the weekend', 'Business vs First Class: honest review', 'Maldives overwater bungalow tour', 'How to travel luxury for less']
  },
  {
    id: 'mock-74', external_id: 'multi-t4', handle: 'budgetbackpacker_bri', full_name: 'Brianna Cole',
    platform: 'YouTube', profile_url: 'https://youtube.com/@budgetbackpacker_bri',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=bri',
    bio: 'Traveling the world on $50/day. Budget travel tips & honest guides.',
    follower_count: 420000, engagement_rate: 4.8, avg_likes: 20160, avg_comments: 1080, avg_views: 155000,
    audience_demographics: { age_18_24: 42, age_25_34: 44, age_35_44: 11, age_45_plus: 3, female: 62, male: 38, top_countries: ['US', 'UK', 'AU'] },
    categories: ['budget-travel', 'backpacking', 'guides'], past_brand_deals: ['travel', 'fashion', 'tech'],
    estimated_cpm: 9, estimated_rate_per_post: 4800, contact_email: 'bri@budgetbackpacker.com',
    location: 'Nomadic', brand_safety_score: 95, fake_follower_percentage: 3.8,
    last_updated: new Date().toISOString(),
    sample_captions: ['Southeast Asia for $1500 (30 days)', 'How to find flights under $200', 'Hostel vs Airbnb: complete breakdown', 'Countries where your money goes furthest', 'Backpacking packing list 2024']
  },
  {
    id: 'mock-75', external_id: 'multi-t5', handle: 'foodtravel_fabio', full_name: 'Fabio Mancini',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@foodtravel_fabio',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=fabio',
    bio: 'Eating my way around the world 🌍 Food, travel & culture. Italian base.',
    follower_count: 2400000, engagement_rate: 7.4, avg_likes: 177600, avg_comments: 8640, avg_views: 3600000,
    audience_demographics: { age_18_24: 48, age_25_34: 38, age_35_44: 11, age_45_plus: 3, female: 58, male: 42, top_countries: ['US', 'IT', 'UK'] },
    categories: ['food-travel', 'food', 'culture'], past_brand_deals: ['food', 'travel', 'beverages'],
    estimated_cpm: 3, estimated_rate_per_post: 18000, contact_email: 'fabio@foodtravelfabio.com',
    location: 'Rome, Italy', brand_safety_score: 91, fake_follower_percentage: 8.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Best street food in Bangkok 🇹🇭', 'Italian vs American pizza comparison', 'I ate only local food for 30 days', 'Worst food I\'ve ever had (honest)', '100% worth it: best meals of 2024']
  },
  {
    id: 'mock-76', external_id: 'multi-t6', handle: 'vanlife_vivian', full_name: 'Vivian Hart',
    platform: 'Instagram', profile_url: 'https://instagram.com/vanlife_vivian',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=vivian',
    bio: 'Living in a van, loving life 🚐 Van build guides & road trip content.',
    follower_count: 285000, engagement_rate: 4.0, avg_likes: 11400, avg_comments: 572, avg_views: 40000,
    audience_demographics: { age_18_24: 36, age_25_34: 50, age_35_44: 11, age_45_plus: 3, female: 65, male: 35, top_countries: ['US', 'CA', 'UK'] },
    categories: ['vanlife', 'adventure', 'lifestyle'], past_brand_deals: ['travel', 'outdoor', 'tech'],
    estimated_cpm: 9, estimated_rate_per_post: 3200, contact_email: 'vivian@vanlifevivian.com',
    location: 'Nomadic (US)', brand_safety_score: 93, fake_follower_percentage: 4.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Van build complete! 🚐 (full tour)', 'Road trip across America: 30 days', 'Van life reality check', 'Costs of living in a van for 1 year', 'Van conversion guide for beginners']
  },
  {
    id: 'mock-77', external_id: 'multi-t7', handle: 'travelwithtyler', full_name: 'Tyler Brooks',
    platform: 'YouTube', profile_url: 'https://youtube.com/@travelwithtyler',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=tylerb',
    bio: 'Family travel content creator. Making the world accessible for families.',
    follower_count: 380000, engagement_rate: 4.2, avg_likes: 15960, avg_comments: 860, avg_views: 140000,
    audience_demographics: { age_18_24: 14, age_25_34: 42, age_35_44: 36, age_45_plus: 8, female: 64, male: 36, top_countries: ['US', 'CA', 'UK'] },
    categories: ['family-travel', 'travel', 'lifestyle'], past_brand_deals: ['travel', 'family', 'tech'],
    estimated_cpm: 9, estimated_rate_per_post: 4600, contact_email: 'tyler@travelwithtyler.com',
    location: 'Nashville, USA', brand_safety_score: 98, fake_follower_percentage: 3.2,
    last_updated: new Date().toISOString(),
    sample_captions: ['Disney World with toddlers: honest guide', 'Best family-friendly destinations 2024', 'How we afford to travel with 3 kids', 'Packing for a family of 5 (carry-on only!)', 'Travel tips every parent needs to know']
  },
  {
    id: 'mock-78', external_id: 'multi-t8', handle: 'adventurecouple_kim', full_name: 'Kim & Jake Lee',
    platform: 'Instagram', profile_url: 'https://instagram.com/adventurecouple_kim',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=kimjake',
    bio: 'Couple traveling the world. Hiking, culture & love stories from the road.',
    follower_count: 445000, engagement_rate: 3.6, avg_likes: 16020, avg_comments: 812, avg_views: 63000,
    audience_demographics: { age_18_24: 30, age_25_34: 50, age_35_44: 16, age_45_plus: 4, female: 70, male: 30, top_countries: ['US', 'UK', 'AU'] },
    categories: ['couple-travel', 'adventure', 'photography'], past_brand_deals: ['travel', 'outdoor', 'fashion', 'tech'],
    estimated_cpm: 8, estimated_rate_per_post: 4900, contact_email: 'kim@adventurecouple.com',
    location: 'Nomadic', brand_safety_score: 93, fake_follower_percentage: 5.0,
    last_updated: new Date().toISOString(),
    sample_captions: ['Proposing at the top of a mountain 💍', 'Traveling as a couple: what we fight about', 'Hiking the Inca Trail together', 'How travel strengthened our relationship', 'Our most romantic destinations']
  },
  {
    id: 'mock-79', external_id: 'multi-t9', handle: 'blacktravels_maya', full_name: 'Maya Thompson',
    platform: 'TikTok', profile_url: 'https://tiktok.com/@blacktravels_maya',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=mayat',
    bio: 'Black travel creator. Curating experiences for Black travelers worldwide.',
    follower_count: 620000, engagement_rate: 8.9, avg_likes: 55180, avg_comments: 2660, avg_views: 920000,
    audience_demographics: { age_18_24: 42, age_25_34: 44, age_35_44: 11, age_45_plus: 3, female: 72, male: 28, top_countries: ['US', 'UK', 'NG'] },
    categories: ['black-travel', 'culture', 'travel'], past_brand_deals: ['travel', 'fashion', 'beauty', 'food'],
    estimated_cpm: 5, estimated_rate_per_post: 5800, contact_email: 'maya@blacktravels.com',
    location: 'Atlanta, USA', brand_safety_score: 94, fake_follower_percentage: 5.5,
    last_updated: new Date().toISOString(),
    sample_captions: ['Countries where I felt most welcome as a Black traveler', 'Traveling to Africa as an African American', 'Safety tips for Black travelers in Europe', 'Most welcoming destinations for Black tourists', 'Cultural connections I felt on this trip']
  },
  {
    id: 'mock-80', external_id: 'multi-t10', handle: 'sustainabletravel_sam', full_name: 'Sam Waters',
    platform: 'Instagram', profile_url: 'https://instagram.com/sustainabletravel_sam',
    avatar_url: 'https://api.dicebear.com/7.x/personas/svg?seed=samw',
    bio: 'Eco-conscious traveler. Sustainable tourism advocate. Leave it better.',
    follower_count: 195000, engagement_rate: 4.4, avg_likes: 8580, avg_comments: 436, avg_views: 27600,
    audience_demographics: { age_18_24: 30, age_25_34: 50, age_35_44: 16, age_45_plus: 4, female: 66, male: 34, top_countries: ['UK', 'US', 'DE'] },
    categories: ['sustainable-travel', 'eco', 'lifestyle'], past_brand_deals: ['sustainable brands', 'travel', 'outdoor'],
    estimated_cpm: 10, estimated_rate_per_post: 2600, contact_email: 'sam@sustainabletravel.com',
    location: 'Copenhagen, Denmark', brand_safety_score: 97, fake_follower_percentage: 3.4,
    last_updated: new Date().toISOString(),
    sample_captions: ['How to travel with almost zero carbon footprint', 'Sustainable hotels that are actually good', 'Overtourism: places to visit vs avoid', 'Eco travel hacks that save money too', 'My commitment to sustainable travel']
  },
]

export function getMockCreatorsByFilters(filters: {
  platform?: string[]
  categories?: string[]
  min_followers?: number
  max_followers?: number
  min_engagement?: number
  location?: string[]
  limit?: number
}): Creator[] {
  let results = [...mockCreators]
  
  if (filters.platform?.length) {
    results = results.filter(c => filters.platform!.includes(c.platform))
  }
  if (filters.categories?.length) {
    results = results.filter(c => c.categories?.some(cat => filters.categories!.includes(cat)))
  }
  if (filters.min_followers) {
    results = results.filter(c => c.follower_count >= filters.min_followers!)
  }
  if (filters.max_followers) {
    results = results.filter(c => c.follower_count <= filters.max_followers!)
  }
  if (filters.min_engagement) {
    results = results.filter(c => c.engagement_rate >= filters.min_engagement!)
  }
  
  return results.slice(0, filters.limit || 20)
}
